name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      database-mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_USER: naphtha
          MYSQL_PASSWORD: naphtha
          MYSQL_DATABASE: naphtha
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

      database-postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: naphtha
          POSTGRES_PASSWORD: naphtha
          POSTGRES_DB: naphtha

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build -p naphtha --all-features --verbose
    - name: Run tests
      run: cargo test -p naphtha --all-features --verbose
