name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports: 
          - 3306:3306
        env:
          MYSQL_USER: naphtha
          MYSQL_PASSWORD: naphtha
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: naphtha
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

      postgres:
        image: postgres:latest
        ports: ['5432:5432']
        env:
          POSTGRES_USER: naphtha
          POSTGRES_PASSWORD: naphtha
          POSTGRES_DB: naphtha
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ job.services.mysql.env.MYSQL_DATABASE }};' -u${{ job.services.mysql.env.MYSQL_USER }} -p${{ job.services.mysql.env.MYSQL_PASSWORD }}
    - name: Build
      run: cargo build -p naphtha --all-features --verbose
    - name: Run tests
      run: cargo test -p naphtha --all-features --verbose
